### ISSUE TITLE
💥 Using Tornado Cash Subgraph Instead of Etherscan API

### ISSUE THREAD

**Issue by tornadocontrib** [pcaversaccio/torn-detector#81]
Would be good in case if we need to query on different chains or if we need to avoid paying etherscan for using their API

**Comment by pcaversaccio** [comment]
> Would be good in case if we need to query on different chains or if we need to avoid paying etherscan for using their API

I agree, but I don't intend to maintain (other than dependencies) / improve the current codebase. Think of this repository as a starting point and not the endgame. So feel free to fork and build on :)
